[[headers]]
  for = "/*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "/*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = max-age=63072000; includeSubDomains; preload
    X-XSS-Protection = 1; mode=block
    X-Content-Type-Options = nosniff
